# docker-compose.yml
version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db
  db:
    image: postgres:latest